name: Cargo Machete
on: [ pull_request ]
jobs:
  cargo-machete:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'src-tauri/Cargo.toml'
              - 'Cargo.lock'
              - 'Cargo.toml'
              - '.github/workflows/machete.yml'
      - name: Machete
        if: steps.filter.outputs.rust == 'true'
        uses: bnjbvr/cargo-machete@main
