name: Lint Rust
on: [ pull_request ]
jobs:
  rust-lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Filter
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            rust:
              - 'src-tauri/Cargo.toml'
              - 'Cargo.lock'
              - 'Cargo.toml'
              - 'src-tauri/build.rs'
              - 'src-tauri/**/*.rs'
              - '.github/workflows/rust-lint.yml'
      - name: Install dependencies
        if: steps.filter.outputs.rust == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Use Node.js
        if: steps.filter.outputs.rust == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - name: Update Rust
        if: steps.filter.outputs.rust == 'true'
        run: rustup update
      - name: Add Clippy
        if: steps.filter.outputs.rust == 'true'
        run: rustup component add clippy
      - name: Rust Format check
        if: steps.filter.outputs.rust == 'true'
        run: cargo fmt -- --check
      - name: Rust Clippy check
        if: steps.filter.outputs.rust == 'true'
        run: cargo clippy -- -D warnings
